# Generated by Django 3.0.6 on 2020-06-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('sampler_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('weight', models.FloatField()),
                ('sex', models.IntegerField(choices=[(1, 'female'), (2, 'male'), (9, 'unknown')])),
                ('maturity', models.IntegerField(choices=[(1, 'female'), (2, 'male'), (9, 'unknown')])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('gonad_weight', models.FloatField(blank=True, null=True)),
                ('parasite', models.NullBooleanField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fish_details', to='samples.Sample')),
            ],
        ),
    ]
